name: Deploy Nuxt.js to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install & Build Nuxt.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate Static Site
        run: npm run generate

      # Deploy Nuxt.js Static Site (ke dalam `public_html/`)
      - name: Deploy Nuxt.js Static Site
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.olami.id
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "dist/"
          server-dir: "/"
